List<Map<String, String>> dummySchedule = [
  {
    "Plan dla toku":
        "Projektowanie i Budowa Jachtów S inż. 3.50 2023/2024 zima",
    "Data zajęć": "2025.06.16 poniedziałek",
    "Czas od": "9:45",
    "Czas do": "10:30",
    "Liczba godzin": "1h00m",
    "Przedmiot": "Właściwości manewrowe jednostek pływających",
    "Forma zajęć": "1",
    "Grupy": "A",
    "Sala": "WChrobrego 112",
    "Prowadzący": "dr hab. inż. st. of. Jarosław Artyszuk",
    "Forma zaliczenia": "Zaliczenie ocena",
    "Uwagi": "",
  },
  {
    "Plan dla toku":
        "Projektowanie i Budowa Jachtów S inż. 3.50 2023/2024 zima",
    "Data zajęć": "2025.06.16 poniedziałek",
    "Czas od": "10:40",
    "Czas do": "11:25",
    "Liczba godzin": "1h00m",
    "Przedmiot": "Właściwości manewrowe jednostek pływających",
    "Forma zajęć": "1",
    "Grupy": "Labor",
    "Sala": "WChrobrego 112",
    "Prowadzący": "dr hab. inż. st. of. Jarosław Artyszuk",
    "Forma zaliczenia": "Zaliczenie ocena",
    "Uwagi": "",
  },
  {
    "Plan dla toku":
        "Projektowanie i Budowa Jachtów S inż. 3.50 2023/2024 zima",
    "Data zajęć": "2025.06.16 poniedziałek",
    "Czas od": "11:45",
    "Czas do": "12:30",
    "Liczba godzin": "1h00m",
    "Przedmiot": "Stateczność i niezatapialność jednostek pływających",
    "Forma zajęć": "1",
    "Grupy": "A",
    "Sala": "WChrobrego 267",
    "Prowadzący": "dr hab. inż. Tomasz Cepowski",
    "Forma zaliczenia": "Egzamin",
    "Uwagi": "",
  },
  {
    "Plan dla toku":
        "Projektowanie i Budowa Jachtów S inż. 3.50 2023/2024 zima",
    "Data zajęć": "2025.06.16 poniedziałek",
    "Czas od": "12:40",
    "Czas do": "14:20",
    "Liczba godzin": "2h00m",
    "Przedmiot": "Stateczność i niezatapialność jednostek pływających",
    "Forma zajęć": "1",
    "Grupy": "Proj",
    "Sala": "WChrobrego 267",
    "Prowadzący": "dr hab. inż. Tomasz Cepowski",
    "Forma zaliczenia": "Zaliczenie ocena",
    "Uwagi": "",
  },
];
